#!/bin/sh


export LD_LIBRARY_PATH=$(/opt/dell/srvadmin/sbin/dsm_om_connsvc-helper)

if ! /opt/dell/srvadmin/sbin/dsm_om_connsvcd -run; then
  echo "Couldn't start dsm_om_connsvc. Exiting."
  exit 1
fi

echo "OMSA running. Browse to port 1311 via https to connect."

while :; do
  if ! pgrep dsm_om_connsvcd > /dev/null; then
    echo "dsm_om_connsvc not running. Exiting."
    exit 1
  fi
  sleep 60
done
